version: "3.3"

services:

  dumper:
    build:
      context: .
      dockerfile: docker-compose/Dockerfile.dumper
    command: [ "daemon" ]
    network_mode: none
    volumes:
      - ./letsencrypt:/data
